export const SERVER_URL = 'https://nmcregistered.org.uk'
// export const SERVER_URL = 'http://localhost:3000'
export const DOCUMENTS_URL = 'https://nmcregistered.org.uk/uploads/'
// export const DOCUMENTS_URL = 'http://localhost:3000/uploads/'
export const GET_ADDRESS_URL = 'https://api.getAddress.io/'