// export const SERVER_URL      = 'http://78.129.165.44:1000'
// export const SERVER_URL = 'http://localhost:8080'
export const SERVER_URL = 'https://nmcregistered.org.uk'
export const DOCUMENTS_URL = 'https://nmcregistered.org.uk/uploads/'
export const GET_ADDRESS_URL = 'https://api.getAddress.io/'